server:
  # start the program -> http://localhost:8082/swagger-ui/index.html
  port: 8082
  shutdown: graceful

spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: true
  main:
    banner-mode: off
  application:
    name: bali-events
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    #    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: 'true'

webdriver:
  local: true

logging:
  level:
    org.zalando.logbook: TRACE
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

