server:
  port: 8082
  shutdown: graceful

spring:
  main:
    banner-mode: off
  application:
    name: data-scrapper
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: 'true'

webdriver:
  local: true

logging:
  level:
    org.zalando.logbook: TRACE
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

