server:
  # start the program -> http://localhost:8080/swagger-ui/index.html
  port: 8083
  shutdown: graceful

logging.level:
  org.springframework.orm.jpa.JpaTransactionManager: DEBUG

spring:
  main:
    banner-mode: off
  application:
    name: bali-events
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    # url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: 'true'

logging:
  level:
    org.zalando.logbook: TRACE
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

com:
  balievent:
    bot:
      token: 6862871633:AAFQEI2mT7sjjiUjfSbgHHYZe7M9xPbjwlg
      username: test_remove_me_sima_bot
